let data = [
  { amount: '378', des: '黑豹防水涂料' },
  { amount: '2100', des: '一车沙' },
  { amount: '1680', des: '3顿水泥' },
  { amount: '36', des: '瓷砖胶' },
  { amount: '11', des: '烟' },
  { amount: '100', des: '借钱' },
  { amount: '900', des: '6平方厘米电线' },
  { amount: '259', des: '2平方厘米电线' },
  { amount: '7000', des: '第一次给包工头钱' },
  { amount: '1500', des: '拉建筑垃圾' },
  { amount: '6000', des: '瓷砖' },
  { amount: '26', des: '填瓷砖的' },
  { amount: '50', des: 'shajiaow' },
  { amount: '50', des: 'shajiaow' },
  { amount: '2100', des: '沙' },
  { amount: '1318', des: '马桶' },
  { amount: '300', des: '吃饭' },
  { amount: '1040', des: '水泥' },
];
